apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: game-server-node-connector
  name: game-server-node-connector
  namespace: 5stack
spec:
  selector:
    matchLabels:
      app: game-server-node-connector
  template:
    metadata:
      labels:
        app: game-server-node-connector
    spec:
      hostNetwork: true
      serviceAccountName: game-server-node-connector
      containers:
        - image: ghcr.io/leonaaardob/game-server-node:latest
          name: game-server-node-connector
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: server-files
              mountPath: /serverfiles
      volumes:
        - name: server-files
          hostPath:
            path: /opt/5stack/serverfiles
            type: Directory
